name: Django CI

on:
  push:
    branches: [ "feature/build-100" ]
  pull_request:
    branches: [ "main-build" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd core
        pytest  # Run your tests
      
    - name: Start Django Server for 1 Minutes
      run: |
        cd core
        python manage.py runserver 0.0.0.0:8000 &  # Run server in background
        SERVER_PID=$!  # Capture the PID of the server
        sleep 60  # Wait for 60 seconds
        kill $SERVER_PID  # Kill the server after 60 seconds
    
    - name: Cooldown Period
      run: |
        echo "Server down. Sleeping for 10 minutes."
        sleep 30   
      
